version: "3.7"
services:
  security-app:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
    privileged: true
    tty: true
