version: "3.7"
services:
  dood-executor-container:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - $(which docker):/usr/bin/docker
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
    tty: true
    extra_hosts: 
      - "memberinfodb-m:127.0.0.1"
      - "memberinfodb-s1:127.0.0.1"
      - "memberinfodb-s2:127.0.0.1"
      - "memberinfodb-s3:127.0.0.1"
      - "memberinfodb-s4:127.0.0.1"
      - "memberinfodb-s5:127.0.0.1"
      - "memberinfodb-s6:127.0.0.1"
      - "memberinfodb-s7:127.0.0.1"
      - "memberinfodb-s8:127.0.0.1"
      - "memberinfodb-s9:127.0.0.1"
      - "memberinfodb-s10:127.0.0.1"
      - "logininfodb-m1:127.0.0.1"
      - "logininfodb-m2:127.0.0.1"
      - "logininfodb-m3:127.0.0.1"
      - "logininfodb-s1:127.0.0.1"
      - "logininfodb-s1-2:127.0.0.1"
      - "logininfodb-s1-3:127.0.0.1"
      - "logininfodb-s2:127.0.0.1"
      - "logininfodb-s2-2:127.0.0.1"
      - "logininfodb-s2-3:127.0.0.1"
      - "logininfodb-s3:127.0.0.1"
      - "logininfodb-s3-2:127.0.0.1"
      - "logininfodb-s3-3:127.0.0.1"
      - "anonymousinfo-db-m:127.0.0.1"
      - "anonymousinfo-db-s:127.0.0.1"
      - "account-db-m:127.0.0.1"
      - "account-db-s:127.0.0.1"
      - "personalinfo-db-m:127.0.0.1"
      - "personalinfo-db-s:127.0.0.1"
      - "memberprivate-nosql:127.0.0.1"
      - "memberprivate-nosql-1:127.0.0.1"
      - "memberprivate-nosql-2:127.0.0.1"
      - "memberprivate-nosql-3:127.0.0.1"
      - "memberprivate-nosql-4:127.0.0.1"
      - "memberprivate-nosql-5:127.0.0.1"
      - "memberpublic-nosql:127.0.0.1"
      - "memberpublic-nosql-1:127.0.0.1"
      - "memberpublic-nosql-2:127.0.0.1"
      - "memberpublic-nosql-3:127.0.0.1"
      - "memberpublic-nosql-4:127.0.0.1"
      - "memberpublic-nosql-5:127.0.0.1"
      - "dmmshared-cache:127.0.0.1"
      - "dmmshared-cache-1:127.0.0.1"
      - "dmmshared-cache-2:127.0.0.1"
      - "dmmshared-cache-3:127.0.0.1"
      - "dmmshared-cache-4:127.0.0.1"
      - "dmmshared-cache-5:127.0.0.1"
      - "dmmshared-cache-6:127.0.0.1"
      - "test-nosql:127.0.0.1"
      - "check-security-test:127.0.0.1"
      - "logger-security-test:127.0.0.1"
      - "check-security.dmm.com:127.0.0.1"
      - "logger-security.dmm.com:127.0.0.1"
      - "connectdb-s:127.0.0.1"
      - "d-provision-db0000.memberapis.dmm.com:127.0.0.1"
      - "cassandra.session.logs.dmm.com:127.0.0.1"
      - "cassandra.general.logs.dmm.com:127.0.0.1"
      - "guest-db-m:127.0.0.1"
      - "guest-db-s:127.0.0.1"

# flyway停止継続
      ##    command: "-configFiles=./conf/account.conf -url=jdbc:mysql://mbe-mysql -schemas=account -password=${MYSQL_PASSWORD} migrate"
    #entrypoint: /bin/sh -c "while :; do sleep 10; done"
